apiVersion: v1
kind: PersistentVolume
metadata:
  name: itunes-collector-pv
  namespace: baabao-itunes
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0a4891959032c766c
